export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_STUDENTS: '/admin/students',
  ADMIN_ADD_STUDENT: '/admin/students/add',
  STUDENTS: '/admin/students',
  ADMIN_TEACHERS: '/admin/teachers',
  TEACHERS: '/admin/teachers',
  ADMIN_ATTENDANCE: '/admin/attendance',
  ATTENDANCE: '/admin/attendance',
  FEES: '/fees',
  ADMIN_TIMETABLE: '/admin/timetable',
  TIMETABLE: '/admin/timetable',
  EXAMINATIONS: '/examinations',
  ACADEMICS: '/academics',
  COMMUNICATION: '/communication',
  ADMIN_NOTICES: '/admin/notices',
  NOTICES: '/admin/notices',
  ADMIN_ROLES_PERMISSIONS: '/admin/roles-permissions',
  ROLES_PERMISSIONS: '/admin/roles-permissions',
  REPORTS: '/reports',
  SETTINGS: '/settings',
};
