import {
  LayoutDashboard,
  Users,
  GraduationCap,
  Building2,
  CalendarCheck,
  DollarSign,
  BookOpen,
  Calendar,
  Megaphone,
  MessageSquare,
  BarChart3,
  Bot,
  ShieldCheck,
  Link,
  FileCheck,
  Book,
} from 'lucide-react';

export const SIDEBAR_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'students', label: 'Students', icon: Users },
  { id: 'teachers', label: 'Teachers', icon: GraduationCap },
  { id: 'classes', label: 'Classes', icon: Building2 },
  { id: 'attendance', label: 'Attendance', icon: CalendarCheck },
  { id: 'fees', label: 'Fees', icon: DollarSign },
  { id: 'homework', label: 'Homework', icon: BookOpen },
  { id: 'timetable', label: 'Timetable', icon: Calendar },
  { id: 'notice-board', label: 'Notice Board', icon: Megaphone },
  { id: 'communication', label: 'Communication', icon: MessageSquare },
  { id: 'reports', label: 'Reports', icon: BarChart3 },
  { id: 'ai-assistant', label: 'AI Assistant', icon: Bot },
  { id: 'roles-permissions', label: 'Roles & Permissions', icon: ShieldCheck },
  { id: 'subject-class', label: 'Subject & Class', icon: Link },
  { id: 'tests-exams', label: 'Tests & Exams', icon: FileCheck },
  { id: 'study-materials', label: 'Study Materials', icon: Book },
];
